### ISSUE TITLE
example/mnist_example.py 

### ISSUE THREAD

**Issue by mrsky007** [lishenghui/blades#16]
hi, i am running mnist_examples.py and confusized about the aggregation and attack strategy parameter settings. Both aggregator and attacker parameter have "num_clients" and "num_byzantine".  Should aggregation and attack strategy parameter set the same or there is other meaning i didn't figure out?
And how can we set a aggregator parameter using no defence strategy which can make a compare about the result of using and not using defence strategy?

**Comment by lishenghui** [comment]
Hi,

Thanks for letting us know about it!

Yes, the parameter list is a bit confusing, we will update this with more details. Both aggregators and attackers require different parameters depending on the strategies.  For example, "num_clients" and "num_byzantine" are needed by "ALIE" attack and "Krum" aggregator according to their assumptions. Please feel free to check the [API references](https://bladesteam.github.io/references/api_reference.html) and their corresponding papers.

When you use "Mean" as an aggregator, the optimization becomes similar to the standard FL algorithms without any defenses.

**Comment by mrsky007** [comment]
Thanks a lot for answering！
