### ISSUE TITLE
Example for Custom Attacker?

### ISSUE THREAD

**Issue by gauenk** [lishenghui/blades#20]
Would you mind helping me make a MWE for a custom attacker? I loved your code so far btw -- it is great. I think the custom aggregator seems easy -- I just pass in my aggregation object. I do not know how to add my own attack code though.

Even if your attack example is super simple, say replacing all compromised gradients with zero, I would love to see an example in a single python file.

Thank you for considering!

**Comment by lishenghui** [comment]
Thanks for your interest!

Yes, we do have an example for custom attacker. Please check our [documentation page ](https://bladesteam.github.io/examples/index.html) for details.

If it doesn't fulfill your requirements, please let us know if there is anything we can improve.
