### ISSUE TITLE
Consine Distance  OR Consine Similarity?

### ISSUE THREAD

**Issue by imamtom** [lishenghui/blades#27]
https://github.com/bladesteam/blades/blob/master/src/blades/aggregators/clustering.py

**Comment by imamtom** [comment]
In line 33, you used "dis_max[i, j] = 1 - spatial.distance.cosine(np_models[i, :], np_models[j, :])", which is Consine Similarity, right?  So in line 39, "clustering = AgglomerativeClustering(affinity='precomputed', linkage='complete', n_clusters=2)", the input distance matrix of  AgglomerativeClustering is 'dis_max'. It should be noted that 'spatial.distance.cosine(vec_a, vec_b)' returns '1-cos(vec_a, vec_b)' . I doubt if cos distance should be used here, because the closer/similar two vectors are, the smaller the distance between these two vectors should be.

**Comment by lishenghui** [comment]
Thanks for pointing out the error. It is fixed now.
