### ISSUE TITLE
about the problem running the todo_cifar10_gpu.py 

### ISSUE THREAD

**Issue by bz2233** [lishenghui/blades#39]
dear prof, when i run todo_cifar10_gpu.py , it sends the error "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" and i don't know how to debug it. Could you please give me some advise?

**Comment by lishenghui** [comment]
Hi @bz2233 , 

Thanks for your feedback. Currently, this file is out of date so I have hidden it from the master branch. It is strongly recommended to run the code with `YAML` configuration files. Please check the [installation guidance](https://github.com/lishenghui/blades#option-b-developer-mode)  for details.

More specifically, you can debug `main.py` in the script folder, by cloning and installing Blades with developer mode with `local_mode: True` in the config file. 

Please let me know if this does not address your concern and I can take a closer look!

**Comment by bz2233** [comment]
Thank you very much! Now I can run the program on GPU perfectly
