### ISSUE TITLE
Awesome work！！

### ISSUE THREAD

**Issue by deepdarkfans** [lishenghui/blades#55]
Hello author. Is it your team that implemented all these defense algorithms? Because I want to add a comparison experiment to my code, but it is not compatible with Blades, so I would like to ask if there is a source code for the defense algorithms. Thank you very much!

**Comment by lishenghui** [comment]
Hi, most of the defenses are implemented on our own. You can check the corresponding paper to see if they did provide a source code for each defense.

**Comment by deepdarkfans** [comment]
> Hi, most of the defenses are implemented on our own. You can check the corresponding paper to see if they did provide a source code for each defense.

Thank you for your answer! I have implemented some of these algorithms in my code and the results are not very bad.
