### ISSUE TITLE
about the experiments' result

### ISSUE THREAD

**Issue by LeeMac24** [lishenghui/blades#73]
First and foremost, I would like to express my support and appreciation for your work on poisoning attack on federated learning.
Additionally, I'm curious to know whether you can reproduce the similar result as the original paper.
Best regards

**Comment by lishenghui** [comment]
Thank you for your kind words and support for my work on poisoning attacks on federated learning.

Regarding your question about the "original paper", could you please specify which paper you are referring to?

Best regards

**Comment by LeeMac24** [comment]
> 

The original paper refers to "Manipulating the Byzantine: Optimizing Model Poisoning Attacks and Defenses for Federated Learning".
I referenced your code to replicate three attack methods: A little is enough, Fang, and Distmax. However, my experimental results indicate that A little is enough performs better than the other two, which is inconsistent with the original Distmax paper's findings.

**Comment by lishenghui** [comment]
Their way of optimizing &gamma; was problematic. I have recently reimplemented their attack using binary search instead. The code is [here](https://github.com/lishenghui/blades/blob/master/blades/adversaries/minmax_adversary.py). Their MinMax attack could sometimes be more effective than A Little is Enough as it re-scales the noise.  But its advantages are not overwhelming. 
 

![fashion_mnist](https://github.com/lishenghui/blades/assets/56755658/95bc5697-fba9-4f1a-940b-f61ed1171897)
![cifar10](https://github.com/lishenghui/blades/assets/56755658/73944390-c85d-40b1-a3bd-01e9401c71cd)

**Comment by LeeMac24** [comment]
Thank you very much for your response.
